### ISSUE TITLE
생성 로직에 대한 이상 발견

### ISSUE THREAD

**Issue by kukjun** [Yu-Jaeyoung/java-working#1]
<img width="590" alt="image" src="https://user-images.githubusercontent.com/63409722/188536700-b03317f4-3848-4b77-92db-30926bc1264f.png">

배열의 0, 1, 2, 3, 4 번째가 비어있음에도 새로 회원가입을 할 수 없음.

<img width="515" alt="image" src="https://user-images.githubusercontent.com/63409722/188536840-590405da-b8a1-4609-8146-3fd32dd9ee4e.png">

* 문제가 되는 코드

**Comment by Yu-Jaeyoung** [comment]
수정 완료하였습니다.
- for 조건문을 추가하여 배열 전체적으로 확인하여 공간이 있는지 여부를 판단
  - count 변수를 선언하여 for문을 통해 배열을 전체적으로 확인할 수 있게 수정
  - (처음에는 count=0으로 선언하였으나, userArray[ ]에 값이 없는 초기에 프로그램이 종료되는 문제가 발생하여 count = -1으로 변수 선언)
  - 마지막에 count와 userArray.legnth의 크기를 비교하여 같을 경우 회원가입이 불가능하게 설정
