### ISSUE TITLE
삭제시 명시적 반환 필요

### ISSUE THREAD

**Issue by kukjun** [Yu-Jaeyoung/java-working#2]
<img width="776" alt="image" src="https://user-images.githubusercontent.com/63409722/188537409-00086924-8ae7-4cca-b222-0181e0aaf737.png">

Scanner 사용 후 close function 부재

**Comment by Yu-Jaeyoung** [comment]
수정 완료하였습니다.
- 입력을 사용할때 키보드를 통해 입력받는 경우도 있지만 파일등을 통해 입력을 받는 경우도 있다. 파일 작업의 순서는 사용하고자 하는 파일을 열고, 사용, 닫기 순서로, 닫지 않을경우 파일이 손상될 수 있으므로, 파일을 열어서 입력을 완료하였을때 닫아야 한다.
- System.in에서 in이 키보드 입력을 가리킨다.
